---
title: "p8105_hw5_ks3663"
author: "Kee-Young Shin"
date: "November 3, 2018"
output: github_document
---

```{r}
library(tidyverse)
library(purrr)
library(RCurl)

```

## Problem 1
```{r}

files_list = paste0("./data/", list.files("./data"))
files_list

output = map_df(files_list, read.csv) %>% 
  add_column(files_list, .before = "week_1") %>% 
  mutate(files_list = str_replace(files_list, "./data/", ""),
         files_list = str_replace(files_list, ".csv", "")) %>% 
  separate(files_list, into = c("Control Arm", "Subject ID"), sep = "_") %>% 
  janitor::clean_names()
output

```

```{r}
# make spaghetti plot comparing both arms 
output %>% 
  gather(key = week, value = observation, week_1:week_8) %>% 
  arrange(control_arm, subject_id) %>% 
  group_by(subject_id) %>% 
  ggplot(aes(x = week, y = observation, color = subject_id, group = subject_id)) + 
    geom_line() + 
    facet_wrap(~control_arm) + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

## Problem 2
```{r}
homicide_df = read.csv(text = getURL("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")) %>% 
  unite(city_state, city:state, sep = ", ") %>% 
  janitor::clean_names()

homicide_df_summarized = homicide_df %>% 
  group_by(city_state) %>% 
  summarize(total_homicide = n(),
      unsolved_homicide = sum(disposition == "Closed without arrest") 
      + sum(disposition == "Open/No arrest"))

homicide_df_summarized

```

```{r}
# run prop.test for Baltimore, MD
baltimore_results = prop.test(x = homicide_df_summarized %>% filter(city_state == "Baltimore, MD") %>% pull(unsolved_homicide), n = homicide_df_summarized %>% filter(city_state == "Baltimore, MD") %>%  pull(total_homicide)) %>% 
  broom::tidy()

# pull estimated proportion and confidence interval
baltimore_results %>% 
  select(estimate, conf.low, conf.high) 

```

```{r}
# run prop.test on all city-states
prop_test_output = homicide_df_summarized %>% 
  group_by(city_state) %>% 
  nest() %>% 
  mutate(output = map2(.x = homicide_df_summarized %>% pull(unsolved_homicide), 
              .y = homicide_df_summarized %>% pull(total_homicide), 
              ~prop.test(x = .x, n = .y)),
         output = map(output, broom::tidy)) %>% 
  select(-data) %>% 
  unnest() %>% 
  select(c("city_state", "estimate", "conf.low", "conf.high"))
  
```

```{r}
# create plot showing estimate for all city-states and their Confidence Intervals
prop_test_output %>% 
  mutate(city_state = as.factor(city_state),
         city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) + 
    geom_point() +
    geom_errorbar(ymin = prop_test_output$conf.low, 
                  ymax = prop_test_output$conf.high) +
    theme(axis.text.x = element_text(angle = 80, hjust = 1))

```

